name: dramix
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  google_mobile_ads: ^6.0.0
  cupertino_icons: ^1.0.8
  google_sign_in: 6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  chewie: ^1.12.1
  get: ^4.6.6
  path_provider: ^2.1.1
  wakelock_plus: ^1.3.2
  firebase_core: ^3.15.1
  firebase_analytics: ^11.6.0
  smooth_page_indicator: ^1.2.1
  firebase_auth: 5.6.2
  googleapis_auth: ^2.0.0
  fluttertoast: ^8.2.4
  ##video_thumbnail: ^0.5.6

  flutter_stripe: ^12.0.1
  flutter_cache_manager: ^3.4.1
  
  ##easy_notify: ^1.0.0
  flutter_gen_runner: ^5.10.0
  firebase_messaging: ^15.2.10
  permission_handler: ^12.0.1
  awesome_notifications: ^0.10.1
  package_info_plus: ^8.3.0
  pull_to_refresh: ^2.0.0
  build_runner: ^2.5.4
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.13.0
  percent_indicator: ^4.2.2
  confetti: ^0.7.0
  webview_flutter_android: ^4.8.2
  dio: ^5.9.0
  flutter_dotenv: ^5.1.0
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: ^0.4.3
  geolocator: ^9.0.2
  countries: ^0.0.5+2
  x509: ^0.2.4+3
  shimmer: ^2.0.0
  in_app_update: ^4.0.1
  animate_do: ^3.0.2
  currency_code_to_currency_symbol: ^0.0.4
  flutter_localization: any
  url_launcher: ^6.2.4
  flutter_credit_card: ^4.1.0
  intl: ^0.20.2
  photo_manager: ^3.0.0
 ## image_gallery_saver: ^1.7.1
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  change_app_package_name: ^1.5.0
  share_plus: ^11.1.0
  device_info_plus: ^11.5.0
  logger: ^2.6.1
  app_links: ^6.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
   
    - assets/icons/
    - assets/images/cinema_background.jpg
    - assets/images/ic_login_tips_google.png
    - assets/images/ic_login_facebook.png
    - assets/images/ic_login_tiktok.png
    - assets/images/ic_rewards_watch_drama_reward_pending.png
    - assets/images/icon_hall_chapter.webp
    - assets/images/icon_gery_press_up.png
    - assets/images/icon_item_video_like_none.webp
    - assets/images/icon_item_video_like.webp
    - assets/images/icon_item_video_collect_40.png
    - assets/images/icon_item_video_collect_none_40.png
    - assets/images/ic_video_more.png
    - assets/images/s.webp
    - assets/images/icon_play_new_36.png
    - assets/images/profile_pic.png
    - assets/icons/ic_store_normal.png
    - assets/icons/ic_store_select.png
    - assets/icons/ic_foru_normal.png
    - assets/icons/ic_foru_select.png
    - assets/images/dramix_logo.png
    - assets/icons/ic_gift_select.png
    - assets/icons/ic_mine_normal.png
    - assets/icons/ic_mine_select.png
    - assets/images/icon_open_eye.png
    - assets/loading.gif
    - assets/coin.png
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/bg3.jpg
    - assets/animations/video_loading.json
    - assets/animations/load-house.json
  generate: true
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dramix_logo.png"